name: Correr los programas y subir la salida
on: push

jobs:
  buildpdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst
        uses: typst-community/setup-typst@v3
        with:
          source_file: aoc2024.typ
      - name: Second week
        run: typst compile aoc2024-week2.typ
      - name: First week
        run: typst compile aoc2024.typ
      - name: Subir el PDF
        uses: actions/upload-artifact@v4
        with:
          name: aoc2024
          path: aoc2024*.pdf
