name: Crear el PDF de la propuesta de tesis
on: push

jobs:
  buildpdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: aoc2025.typ
      - name: Subir el PDF
        uses: actions/upload-artifact@v4
        with:
          name: aoc2025.pdf
          path: aoc2025.pdf
